language: python
python:
- 3.7
install:
- pip install -r requirements.txt
before_script:
- python manage.py migrate
# - python manage.py collectstatic --noinput
script:
- black . --exclude 'tests\.py|polls/migrations/.*'
- flake8 .
- coverage run --source=mySites,polls manage.py test
after_script:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secrect_access_key: $AWS_SECRECT_ACCESS_KEY
  region: us-west-2
  app: django-polls-app
  env: django-polls-app-env
  # bucket_name: the-target-S3-bucket

env:
  global:
  - secure: J7MvDLvE3pSicv1Ib5Gc0XSM9sQbDkaoc67/MUiE0oSI+Ijtm/WZVe2cPa/OkUVIXKrbkG1dtgqnxGIPAlscsTy22jNbc2bPe1i4E9nPh9xXvRkfNX8SlVgsk3fdZUPMAhuapRcBHV/Y+cPHyPrCvwMTcriQHXHQeP2x8hmZ9rudVVnDsXnNDgpXZP0kXRDjnOT6CdOj/KblUA3ZauREqmw9CpnIMmtNL1WNh0l1DkkbGKdiaIi0KdYx+n8ew/qt6BZ+yFUEyYGkJNF6BfenJ3u3OEZjssRXb2DVDxm96zYpbv/v0AwU3CuR0bEF9le2QyD4OsHZzmxAIkIeRsK0D5Wo1/eQp6D7cxQlF2n9DMbWoRBLvoufKT0eilnNzxfYWBbGu5MC5OaH1gImDPlTj0tpwe9En7NDLWQs4OMY5TTQfebv4xZaXymJv+yWimNzJgAUAr57ItRrQvtN1XBmBOaNQxIGQWsKj+frCntHcOtjyYyDhYzPuuaXUNgyf+EiztXl2iXaHaHnxPX5Qrne7wpjfj0VPfSZDOj3p58FWEqHuP1abFSLT92D/uBFUHboDebdj8BiFEHM20zy9Ozjoo0XmSbZmU7Qzfr9Nww2q0zmLt0gbQ5ZD2iKRFf5Hv0QvhDOMyGNSkqS4uc0P+q60bTAPpS+UX8TmNn8Ofx7NQg=
  - secure: Dsrr2nkwyOqfdZLPE/9MI1EWpIlkwe6nyBB6DuYMgcqhNIjkHcUPT2pY2XDYXfepnWpH1OqwVjjX55cytIvsiTI0TbD1pAfiBpgex+AQHJqEsdWOiWNvqN+K0VlTcRC7GsmVk2gDKYVSEcKIef+N5ZqY/smj/NXjTTv2GUZggTdDwNh4VkoP0kCLZ+OlJtjyIzScjGksSENh7GYvaw77jSr/0C+f8CYNdTlle+lja5Zz/GBF0sTN626I+3Igc61YiKJb3L+glMM8wTU5y5gDyKoIEVa7FD+HhofaBRxoH3lU/qVOPNoy0ITi7zfyNRbn61D6dNWOJUzxzoBwEUiEXnpn+yZDWLKMLNxm4qmPFuoqXOTMe4Tpfd7dGxQoaUc7xt6ar81j3cau3CUbgBKDdwOgMSHqletC0GQ1ZvhSAEnAvoDbiXNiBMvbqenv8+SmxjcOyWhhaD1xut0U0RdpzH2CkjTgA9x76hqPnI4ziqi3KTSYa2DJmei8aAxkaGqbcCkCH6iULTNPn+KGxgx1YEAKHbsWNb1q8IAohifwwbwLAbzvMszS5f70G+9fBRyTxaQNFHEKB9hOceMeBVfb/aERqU1Hwbrw1aj5NXQlT4i6qZMu55J7KouqLV68AC6n6VwS4tna/HOv8rQqEu1lreA2rDUu+pD3bk9cp0pgltM=
